const cloud = require('wx-server-sdk')

cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV })
const db = cloud.database()

const ACTIVITY_COVER_MAP = {
  'lz-yuzhong-strawberry-family-day': '/images/activities/lz-yuzhong-strawberry-family-day.jpg',
  'lz-gaolan-country-photo-day': '/images/activities/lz-gaolan-country-photo-day.jpg',
  'lz-yongdeng-rose-weekend': '/images/activities/lz-yongdeng-rose-weekend.jpg',
  'lz-suburb-farm-study-camp': '/images/activities/lz-suburb-farm-study-camp.jpg',
  'lz-bailihe-handmade-food-tour': '/images/activities/lz-bailihe-handmade-food-tour.jpg',
  'lz-kushui-rose-culture-day': '/images/nav-academy.png',
  'lz-kushui-danxia-hike-day': '/images/nav-academy.png',
  'lz-xigu-baihe-culture-day': '/images/nav-academy.png',
  'lz-gaolan-shichuan-pear-garden-day': '/images/nav-academy.png',
  'tianshui-qinan-fruit-pick-day': '/images/activities/tianshui-qinan-fruit-pick-day.jpg',
  'zhangye-rural-homestay-weekend': '/images/activities/zhangye-rural-homestay-weekend.jpg',
  'longnan-tea-hill-folk-experience': '/images/activities/longnan-tea-hill-folk-experience.jpg',
  'linxia-food-culture-village-tour': '/images/activities/linxia-food-culture-village-tour.jpg',
  'gannan-ranch-life-light-tour': '/images/activities/gannan-ranch-life-light-tour.jpg',
}

function getActivityAssets(seedKey) {
  const cover = ACTIVITY_COVER_MAP[seedKey] || '/images/activities/lz-yuzhong-strawberry-family-day.jpg'
  return {
    cover,
    gallery: [cover],
  }
}

const seedActivities = [
  {
    seedKey: 'lz-yuzhong-strawberry-family-day',
    title: '兰州榆中亲子草莓采摘一日行',
    summary: '适合周末带娃出发的近郊田园体验，兼顾采摘乐趣、农事科普和乡村午餐。',
    content: '从兰州市区出发约一小时可抵达榆中近郊草莓种植基地。行程以亲子家庭为主线，上午进入温室大棚采摘当季草莓，认识常见种植方式和田间管理知识；中午安排农家土灶午餐，下午补充萌宠互动、手作草莓果酱体验和田园自由拍照时间。整体节奏轻松，适合周末短途出行。',
    detail: '活动亮点包括：1. 当季草莓不限时采摘体验；2. 适合儿童参与的农事科普讲解；3. 农家午餐与亲子手作相结合；4. 场地平整，老人和儿童都能轻松参与。建议穿着轻便、防滑鞋，现场可购买草莓伴手礼和果酱礼盒。',
    province: '甘肃省',
    city: '兰州市',
    district: '榆中县',
    locationName: '榆中县和平镇近郊草莓园',
    cover: getActivityAssets('lz-yuzhong-strawberry-family-day').cover,
    gallery: getActivityAssets('lz-yuzhong-strawberry-family-day').gallery,
    days: 1,
    durationText: '1天',
    price: 168,
    priceFrom: 168,
    tags: ['乡村', '农旅', '亲子', '采摘', '周末短途'],
    travelModeTags: ['亲子出行', '周末短途'],
    playTags: ['种植采摘', '农事科普', '乡村美食', '创意摄影'],
    suitableGroups: ['亲子家庭', '都市白领'],
    highlights: ['温室草莓采摘', '农家午餐', '亲子手作果酱', '田园拍照'],
    itinerary: [
      '09:00 兰州市区集合出发',
      '10:00 到达草莓园，进行采摘与农事讲解',
      '12:00 农家午餐',
      '13:30 草莓果酱手作与萌宠互动',
      '15:30 返程'
    ],
    pickup: true,
    pickupPoint: '兰州市城关区指定地铁口集合',
    transport: '往返旅游大巴 / 自驾可选',
    stay: '不含住宿',
    status: 'published',
    traveledCount: 126
  },
  {
    seedKey: 'lz-gaolan-country-photo-day',
    title: '兰州皋兰田园风光摄影体验日',
    summary: '围绕黄河沿线乡村田园与农耕景观展开的摄影轻体验，适合朋友结伴和独自出行。',
    content: '皋兰县沿黄河乡村拥有独特的田园色块与村落景观，春夏适合拍花海与农田，秋季适合拍丰收与村庄纹理。活动由本地领队带路，串联观景点、田埂漫步和简短摄影构图分享，适合想拍出生活感与乡村风貌的用户。',
    detail: '本行程不以高强度打卡为目标，而是强调慢下来观察乡村环境。活动包含两处摄影点位、一个休息驿站和一顿乡村简餐。建议携带手机或相机，喜欢拍人像和风景的用户都能找到适合的角度。',
    province: '甘肃省',
    city: '兰州市',
    district: '皋兰县',
    locationName: '皋兰县黄河沿线田园观景带',
    cover: getActivityAssets('lz-gaolan-country-photo-day').cover,
    gallery: getActivityAssets('lz-gaolan-country-photo-day').gallery,
    days: 1,
    durationText: '1天',
    price: 138,
    priceFrom: 138,
    tags: ['乡村', '摄影', '文旅', '田园', '周末短途'],
    travelModeTags: ['独自旅行', '闺蜜出游', '老友聚行'],
    playTags: ['创意摄影', '生态观光', '乡村漫游'],
    suitableGroups: ['青年社交族', '都市白领'],
    highlights: ['田园摄影点位', '黄河乡村风貌', '慢节奏漫游', '本地领队带看'],
    itinerary: [
      '08:30 市区集合出发',
      '09:40 抵达皋兰观景点，摄影自由创作',
      '12:00 乡村简餐',
      '13:30 第二摄影点位与构图分享',
      '16:00 返程'
    ],
    pickup: true,
    pickupPoint: '兰州市安宁区商圈附近集合',
    transport: '旅游小巴',
    stay: '不含住宿',
    status: 'published',
    traveledCount: 88
  },
  {
    seedKey: 'lz-yongdeng-rose-weekend',
    title: '兰州永登玫瑰主题乡村微度假',
    summary: '适合情侣、闺蜜和轻休闲人群的周末玫瑰主题微度假，兼顾观光、手作与民宿体验。',
    content: '依托永登县玫瑰相关乡村资源设计的两天一晚微度假线路，包含玫瑰花田观光、玫瑰纯露手作体验、乡村晚餐和精品民宿入住。整体强调慢下来、住下来、拍下来，是适合城市年轻人短途放松的轻度假选择。',
    detail: '行程节奏舒缓，适合想从城市切换到乡野状态的用户。活动包含玫瑰花田打卡、手作体验、民宿下午茶和周边乡村步道漫游。价格以双人房为基础，适合情侣和朋友结伴，也可加价升级独栋房型。',
    province: '甘肃省',
    city: '兰州市',
    district: '永登县',
    locationName: '永登县玫瑰主题乡村民宿群',
    cover: getActivityAssets('lz-yongdeng-rose-weekend').cover,
    gallery: getActivityAssets('lz-yongdeng-rose-weekend').gallery,
    days: 2,
    durationText: '2天1晚',
    price: 468,
    priceFrom: 468,
    tags: ['乡村', '民宿', '摄影', '康养', '文旅'],
    travelModeTags: ['闺蜜出游', '老友聚行', '私人定制'],
    playTags: ['栖居山野', '民宿深度体验', '创意摄影', '手工工坊'],
    suitableGroups: ['都市白领', '青年社交族'],
    highlights: ['玫瑰花田打卡', '纯露手作', '精品民宿入住', '乡村微度假'],
    itinerary: [
      'Day1 上午 市区出发前往永登',
      'Day1 中午 入住民宿，享用乡村午餐',
      'Day1 下午 玫瑰花田观光与手作体验',
      'Day1 晚上 乡村晚餐与自由休闲',
      'Day2 上午 周边村落慢游后返程'
    ],
    pickup: true,
    pickupPoint: '兰州市七里河区指定集合点',
    transport: '旅游巴士 / 自驾可选',
    stay: '精品民宿1晚',
    status: 'published',
    traveledCount: 73
  },
  {
    seedKey: 'lz-suburb-farm-study-camp',
    title: '兰州近郊农事研学亲子体验营',
    summary: '面向亲子与研学师生的农事主题体验，涵盖播种、喂养、科普与团队协作。',
    content: '该活动以兰州近郊农庄为载体，围绕“认识农作物、认识土地、认识节气”设计研学内容。包括农作物播种、蔬菜采收、家禽喂养和农具认知等互动环节，适合学校研学、亲子家庭和周末小团活动。',
    detail: '活动场地较开阔，配有基础研学教室和卫生设施。老师会根据年龄层调整讲解内容，小朋友可通过任务卡完成观察与记录。适合希望孩子多接触自然、增强动手能力的家庭。',
    province: '甘肃省',
    city: '兰州市',
    district: '兰州新区',
    locationName: '兰州新区农事研学基地',
    cover: getActivityAssets('lz-suburb-farm-study-camp').cover,
    gallery: getActivityAssets('lz-suburb-farm-study-camp').gallery,
    days: 1,
    durationText: '1天',
    price: 198,
    priceFrom: 198,
    tags: ['研学', '亲子', '农旅', '劳动', '乡村'],
    travelModeTags: ['亲子出行', '团队出游'],
    playTags: ['农事科普', '农事劳动体验', '体验派'],
    suitableGroups: ['亲子家庭', '研学师生'],
    highlights: ['农事任务卡', '播种采收体验', '家禽喂养互动', '节气知识讲解'],
    itinerary: [
      '09:00 集合前往研学基地',
      '10:00 农作物科普与任务分组',
      '11:00 播种、采收与喂养体验',
      '12:30 简餐与休息',
      '13:30 农具认知与节气课堂',
      '15:30 总结返程'
    ],
    pickup: true,
    pickupPoint: '兰州新区地铁站附近',
    transport: '团队巴士',
    stay: '不含住宿',
    status: 'published',
    traveledCount: 154
  },
  {
    seedKey: 'lz-bailihe-handmade-food-tour',
    title: '兰州百合主题乡味手作体验',
    summary: '把兰州特色百合与乡味手作结合在一起的半日体验，适合城市游客带走一份有记忆点的甘肃味道。',
    content: '以兰州百合为主题，围绕百合食材展开识别、讲解和手作体验。用户可了解百合种植与加工方式，现场参与甜品或家常小食制作，并选购礼盒、干货或调味伴手礼。适合轻松体验型用户，也适合作为城市游客的短时特色行程。',
    detail: '活动主打“可体验、可带走、可分享”，通过百合这一甘肃在地物产，让用户在短时间内建立对本地乡味的感知。场地以手作教室和展示区为主，流程轻松，不会太累。',
    province: '甘肃省',
    city: '兰州市',
    district: '七里河区',
    locationName: '兰州百合乡味体验馆',
    cover: getActivityAssets('lz-bailihe-handmade-food-tour').cover,
    gallery: getActivityAssets('lz-bailihe-handmade-food-tour').gallery,
    days: 0.5,
    durationText: '半天',
    price: 128,
    priceFrom: 128,
    tags: ['乡味', '手作', '文旅产品', '美食', '体验'],
    travelModeTags: ['独自旅行', '闺蜜出游', '周末短途'],
    playTags: ['乡村美食', '手工工坊', '体验派'],
    suitableGroups: ['都市白领', '青年社交族', '银发族'],
    highlights: ['百合主题手作', '甘肃在地食材', '可带走伴手礼', '轻松半日体验'],
    itinerary: [
      '14:00 到店签到与百合知识介绍',
      '14:30 百合手作体验',
      '15:30 百合相关产品试吃与选购',
      '16:30 自由交流结束'
    ],
    pickup: false,
    pickupPoint: '',
    transport: '自行到达',
    stay: '不含住宿',
    status: 'published',
    traveledCount: 61
  },
  {
    seedKey: 'lz-kushui-rose-culture-day',
    title: '苦水玫瑰季·田园美食与非遗文化体验',
    summary: '以万亩玫瑰采摘、丹霞风光与非遗制作为核心的一日线路，适合赏花、美食与文化体验型用户。',
    content: '线路围绕永登苦水玫瑰核心产区展开，串联玫瑰花田观光、农家风味午餐、玫瑰主题非遗工坊与丹霞风貌打卡。活动节奏舒缓，既能满足周末短途出游的轻松感，也能让用户在一日内建立对苦水玫瑰地域文化的完整感知。',
    detail: '上午进入玫瑰园进行采摘与花海打卡，中午安排地方农家餐，下午进入工坊体验玫瑰酱或精油蒸馏制作，并结合丹霞观景点收尾。适合朋友结伴、亲子家庭与偏好文化型内容的用户。',
    province: '甘肃省',
    city: '兰州市',
    district: '永登县',
    locationName: '苦水玫瑰田园综合体',
    cover: getActivityAssets('lz-kushui-rose-culture-day').cover,
    gallery: getActivityAssets('lz-kushui-rose-culture-day').gallery,
    days: 1,
    durationText: '1天',
    price: 228,
    priceFrom: 228,
    tags: ['玫瑰', '赏花', '非遗', '乡村', '文旅', '周末短途'],
    travelModeTags: ['老友聚行', '亲子出行', '周末短途', '独自旅行'],
    playTags: ['玫瑰采摘', '乡村美食', '非遗文化', '丹霞观光', '体验派'],
    suitableGroups: ['亲子家庭', '都市白领', '青年社交族'],
    highlights: ['万亩苦水玫瑰采摘体验', '丹霞地貌与玫瑰花海同框打卡', '非遗玫瑰酱/精油蒸馏制作', '地方风味农家餐品尝'],
    itinerary: [
      '08:30 兰州市区集合',
      '10:00 抵达苦水玫瑰园',
      '10:30 采摘与花田打卡',
      '12:30 农家午餐',
      '14:00 非遗工坊体验',
      '16:30 返回'
    ],
    pickup: true,
    pickupPoint: '兰州市区商圈集合点',
    transport: '小巴往返 / 自驾',
    stay: '不含住宿',
    status: 'published',
    traveledCount: 45,
    sourceType: 'real'
  },
  {
    seedKey: 'lz-kushui-danxia-hike-day',
    title: '苦水丹霞·红色地貌与田园风光轻徒步',
    summary: '以丹霞地貌观光、田园漫步为核心的一日线路，适合摄影、户外与自然爱好者。',
    content: '本线路带你走进苦水丹霞，观赏红、橙、黄相间的层理地貌，在小众机位拍摄田园与丹霞同框的画面，并安排低强度轻徒步与自然科普内容。整体节奏舒适，兼顾观景、拍照和周末放松。',
    detail: '路线包含约3公里低难度轻徒步，适合全年龄段参与。领队会补充丹霞形成的地质知识，并带领用户在观景平台、步道节点和田园边界完成拍摄与休憩。',
    province: '甘肃省',
    city: '兰州市',
    district: '永登县',
    locationName: '苦水丹霞地质公园',
    cover: getActivityAssets('lz-kushui-danxia-hike-day').cover,
    gallery: getActivityAssets('lz-kushui-danxia-hike-day').gallery,
    days: 1,
    durationText: '1天',
    price: 198,
    priceFrom: 198,
    tags: ['丹霞', '徒步', '摄影', '乡村', '文旅', '周末短途'],
    travelModeTags: ['老友聚行', '亲子出行', '摄影团', '独自旅行'],
    playTags: ['丹霞观光', '轻徒步', '创意摄影', '田园漫步', '自然科普'],
    suitableGroups: ['青年社交族', '亲子家庭', '都市白领'],
    highlights: ['红色丹霞层理地貌全景打卡', '田园与丹霞同框的小众机位', '3km低难度轻徒步路线', '适合轻松出行与摄影爱好者'],
    itinerary: [
      '08:30 兰州市区集合',
      '10:00 抵达苦水丹霞',
      '10:20 轻徒步与摄影',
      '12:30 农家午餐',
      '14:00 田园漫步',
      '16:30 返回'
    ],
    pickup: true,
    pickupPoint: '兰州市区商圈集合点',
    transport: '小巴往返 / 自驾',
    stay: '不含住宿',
    status: 'published',
    traveledCount: 32,
    sourceType: 'real'
  },
  {
    seedKey: 'lz-xigu-baihe-culture-day',
    title: '兰州西果园百合田园文化体验',
    summary: '把兰州百合种植采摘、非遗美食与百年乡村文化结合的一日线路，适合美食与农耕体验优先型用户。',
    content: '线路围绕西果园百合文化体验带展开，串联百年百合田观光、百合主题风味午餐、百合非遗工坊、田园漫步和伴手礼选购。整体体验偏在地生活方式，适合朋友结伴、家庭亲子及注重健康饮食的用户。',
    detail: '用户可走进海拔1900米以上的百合田，了解兰州百合的生长环境与百年产业故事，并通过挖掘、分拣、手作或风味品鉴等环节建立完整认知。体验结束可领取定制百合小卡并选购伴手礼。',
    province: '甘肃省',
    city: '兰州市',
    district: '七里河区',
    locationName: '西果园百合文化体验带',
    cover: getActivityAssets('lz-xigu-baihe-culture-day').cover,
    gallery: getActivityAssets('lz-xigu-baihe-culture-day').gallery,
    days: 1,
    durationText: '1天',
    price: 258,
    priceFrom: 258,
    tags: ['百合', '美食', '农耕体验', '非遗文化', '周末短途', '亲子研学', '健康养生', '出片打卡'],
    travelModeTags: ['老友聚行', '亲子出行', '周末短途', '银发康养'],
    playTags: ['乡村美食', '百合非遗', '田园观光', '农耕体验', '治愈放松', '亲子研学'],
    suitableGroups: ['亲子家庭', '都市白领', '银发族'],
    highlights: ['深入百年百合田了解生长密码', '品尝百合全席风味午餐', '亲手参与百合采摘/分拣', '聆听130年种植史与产业故事', '赠送定制百合小卡'],
    itinerary: [
      '09:00 兰州市区指定商圈集合',
      '10:30 抵达西果园百合文化体验带',
      '11:30 品尝百合风味午餐',
      '13:30 参观百合非遗工坊并体验采摘/分拣',
      '16:00 领取定制百合小卡并返程'
    ],
    pickup: true,
    pickupPoint: '兰州市区商圈集合点',
    transport: '小巴往返',
    stay: '不含住宿',
    status: 'published',
    traveledCount: 55,
    sourceType: 'real'
  },
  {
    seedKey: 'lz-gaolan-shichuan-pear-garden-day',
    title: '皋兰什川古梨园一日体验',
    summary: '以百年古梨园、农耕文化与非遗体验为核心的一日路线，适合家庭、朋友及银发群体周末轻出行。',
    content: '线路以“百年梨园+农耕文化+非遗体验”为核心，带领游客漫步万亩古梨园，感受“世界第一古梨园”的生态魅力；中午安排梨园特色农家餐，下午根据人群偏好选择农耕互动或非遗手工体验。',
    detail: '适合亲子、老友与银发群体参与，节奏舒缓，重点不在高强度打卡，而在于用一整天完整体验皋兰什川的梨园生态、黄河农耕文化与乡土手作记忆。',
    province: '甘肃省',
    city: '兰州市',
    district: '皋兰县',
    locationName: '皋兰什川古梨园',
    cover: getActivityAssets('lz-gaolan-shichuan-pear-garden-day').cover,
    gallery: getActivityAssets('lz-gaolan-shichuan-pear-garden-day').gallery,
    days: 1,
    durationText: '1天',
    price: 198,
    priceFrom: 198,
    tags: ['梨园', '农耕', '非遗', '亲子', '踏青', '摄影'],
    travelModeTags: ['亲子出行', '老友聚行', '周末短途', '银发休闲'],
    playTags: ['梨园观光', '农耕体验', '非遗手工', '农家美食', '摄影打卡'],
    suitableGroups: ['亲子家庭', '老友结伴行', '银发族'],
    highlights: ['百年古梨园沉浸式观光', '地道农家风味餐食', '非遗剪纸/皮影体验', '农耕劳作亲子互动', '专业讲解古梨文化与黄河风情'],
    itinerary: [
      '08:30 兰州城区指定地点集合出发',
      '10:00 抵达皋兰什川古梨园',
      '10:15 古梨园观光与古梨文化讲解',
      '12:00 农家特色午餐',
      '13:30 农耕体验或非遗手工',
      '15:30 梨园摄影自由活动',
      '16:30 集合返程'
    ],
    pickup: true,
    pickupPoint: '兰州城区指定商圈集合点',
    transport: '大巴往返',
    stay: '不含住宿',
    status: 'published',
    traveledCount: 60,
    sourceType: 'real'
  },
  {
    seedKey: 'tianshui-qinan-fruit-pick-day',
    title: '天水秦安果园采摘与乡村漫游',
    summary: '围绕天水果乡资源设计的采摘慢游线路，适合家庭出行和周末短途放松。',
    content: '秦安是甘肃知名果业产区之一，活动结合当季果园采摘、乡村漫游和地方小吃体验展开。春夏可体验果园观景与农事讲解，秋季则重点转向采摘与丰收感受。整体线路适合城市家庭、朋友结伴和自驾游客。',
    detail: '行程以轻松为主，不安排高强度打卡。除了果园采摘，还会串联村落步道、乡间小卖部和农家小院，适合喜欢慢逛、拍照和体验在地风味的人群。',
    province: '甘肃省',
    city: '天水市',
    district: '秦安县',
    locationName: '秦安县果园采摘体验区',
    cover: getActivityAssets('tianshui-qinan-fruit-pick-day').cover,
    gallery: getActivityAssets('tianshui-qinan-fruit-pick-day').gallery,
    days: 1,
    durationText: '1天',
    price: 188,
    priceFrom: 188,
    tags: ['乡村', '采摘', '田园', '亲子', '农旅'],
    travelModeTags: ['亲子出行', '老友聚行', '周末短途'],
    playTags: ['种植采摘', '生态观光', '乡村漫游', '乡村美食'],
    suitableGroups: ['亲子家庭', '都市白领', '银发族'],
    highlights: ['当季果园采摘', '天水乡村漫游', '在地风味小吃', '适合自驾'],
    itinerary: [
      '09:30 果园集合签到',
      '10:00 果园采摘与讲解',
      '12:00 农家午餐',
      '13:30 乡村步道漫游与拍照',
      '16:00 自由返程'
    ],
    pickup: false,
    pickupPoint: '',
    transport: '自驾优先 / 可拼车',
    stay: '不含住宿',
    status: 'published',
    traveledCount: 97
  },
  {
    seedKey: 'zhangye-rural-homestay-weekend',
    title: '张掖乡野栖居民宿慢享两日游',
    summary: '围绕河西乡野风貌和民宿休闲体验设计的慢节奏两日游，适合想住下来的人。',
    content: '张掖周边乡野兼具西北开阔感和民宿静享氛围，活动以“住进乡野”作为核心体验，搭配日落观景、地方美食和周边乡村散步。适合周末度假、情侣朋友结伴以及想切换生活节奏的人群。',
    detail: '入住的是带公区与庭院的乡野民宿，行程不追求点位堆砌，而是强调休息、景观和氛围。适合想放空、想拍照、想换环境的人群。部分日期可加订星空观景或乡村烤炉晚餐。',
    province: '甘肃省',
    city: '张掖市',
    district: '甘州区',
    locationName: '张掖乡野民宿聚落',
    cover: getActivityAssets('zhangye-rural-homestay-weekend').cover,
    gallery: getActivityAssets('zhangye-rural-homestay-weekend').gallery,
    days: 2,
    durationText: '2天1晚',
    price: 598,
    priceFrom: 598,
    tags: ['民宿', '康养', '乡村', '文旅', '摄影'],
    travelModeTags: ['闺蜜出游', '老友聚行', '私人定制'],
    playTags: ['栖居山野', '民宿深度体验', '生态观光', '创意摄影'],
    suitableGroups: ['都市白领', '青年社交族', '银发族'],
    highlights: ['乡野民宿入住', '日落观景', '地方风味晚餐', '慢节奏休闲'],
    itinerary: [
      'Day1 下午 抵达民宿办理入住',
      'Day1 傍晚 日落观景与自由拍照',
      'Day1 晚上 地方风味晚餐',
      'Day2 上午 乡村散步与慢享早餐后返程'
    ],
    pickup: false,
    pickupPoint: '',
    transport: '自驾 / 高铁转接驳',
    stay: '乡野民宿1晚',
    status: 'published',
    traveledCount: 52
  },
  {
    seedKey: 'longnan-tea-hill-folk-experience',
    title: '陇南茶乡山居民俗体验行',
    summary: '适合喜欢山地景观与民俗体验的用户，在茶乡氛围里感受甘肃南部的生活节奏。',
    content: '陇南部分地区兼具山地风景、茶园景观和在地民俗文化，活动围绕茶乡步道、农家餐食和民俗互动展开。适合希望体验不一样甘肃气质的用户，也适合对民俗文化和山地风景感兴趣的人群。',
    detail: '行程偏体验型，除了基础观光，还会安排茶园慢行、手作尝试和村落交流。对于拍照、品茶、体验在地生活的人来说，这条路线很有记忆点。',
    province: '甘肃省',
    city: '陇南市',
    district: '康县',
    locationName: '康县茶乡山居体验区',
    cover: getActivityAssets('longnan-tea-hill-folk-experience').cover,
    gallery: getActivityAssets('longnan-tea-hill-folk-experience').gallery,
    days: 2,
    durationText: '2天1晚',
    price: 528,
    priceFrom: 528,
    tags: ['乡村', '民俗', '康养', '文旅', '生态'],
    travelModeTags: ['独自旅行', '老友聚行', '私人定制'],
    playTags: ['非遗文化', '生态观光', '栖居山野', '体验派'],
    suitableGroups: ['都市白领', '银发族'],
    highlights: ['茶乡山居体验', '民俗互动', '山地步道', '地方风味餐食'],
    itinerary: [
      'Day1 抵达康县，入住山居民宿',
      'Day1 下午 茶园步道慢行与村落探访',
      'Day1 晚上 民俗晚餐',
      'Day2 上午 茶乡体验后返程'
    ],
    pickup: false,
    pickupPoint: '',
    transport: '自驾优先',
    stay: '山居民宿1晚',
    status: 'published',
    traveledCount: 43
  },
  {
    seedKey: 'linxia-food-culture-village-tour',
    title: '临夏河州美食与乡村文化体验',
    summary: '把临夏地方风味和乡村文化参观结合起来的一日线路，适合美食优先型用户。',
    content: '临夏的在地饮食与河州文化有很强辨识度，本活动围绕“吃 + 看 + 体验”展开，适合想把美食作为旅行重点的用户。行程包含地方特色餐食体验、乡村文化点位参观和轻度步行游览。',
    detail: '除了品尝在地风味，本线路还会通过领队讲解让用户了解部分饮食背后的地域文化。整体节奏舒适，适合朋友结伴、家庭出行和银发用户。',
    province: '甘肃省',
    city: '临夏回族自治州',
    district: '临夏市',
    locationName: '河州乡味文化体验带',
    cover: getActivityAssets('linxia-food-culture-village-tour').cover,
    gallery: getActivityAssets('linxia-food-culture-village-tour').gallery,
    days: 1,
    durationText: '1天',
    price: 228,
    priceFrom: 228,
    tags: ['美食', '乡村', '文旅', '周末短途', '民俗'],
    travelModeTags: ['老友聚行', '亲子出行', '周末短途'],
    playTags: ['乡村美食', '非遗文化', '体验派'],
    suitableGroups: ['银发族', '都市白领', '老友聚行'],
    highlights: ['河州风味美食', '乡村文化点位', '地方讲解', '适合轻松出行'],
    itinerary: [
      '09:00 指定地点集合',
      '10:30 抵达河州乡味体验带',
      '11:30 风味午餐',
      '13:30 乡村文化点位参观',
      '16:00 返程'
    ],
    pickup: true,
    pickupPoint: '临夏市区商圈集合点',
    transport: '小巴往返',
    stay: '不含住宿',
    status: 'published',
    traveledCount: 69
  },
  {
    seedKey: 'gannan-ranch-life-light-tour',
    title: '甘南草原牧场生活轻体验',
    summary: '以草原牧场生活感受为核心的轻体验活动，适合想感受高原草地与牧场氛围的用户。',
    content: '该活动围绕甘南草原边缘牧场展开，内容包括牧场步行、简单牧场互动、草地休闲和风味餐食体验。相比深度高海拔线路，这条更偏入门型体验，更适合想感受草原生活但不想高强度奔波的用户。',
    detail: '活动整体偏轻体验和拍照观景，重点是让用户感受草原与牧场生活氛围。建议穿着保暖、防晒，适合朋友结伴与小团出行。部分日期可叠加营地晚餐或星空观景项目。',
    province: '甘肃省',
    city: '甘南藏族自治州',
    district: '夏河县',
    locationName: '夏河牧场轻体验营地',
    cover: getActivityAssets('gannan-ranch-life-light-tour').cover,
    gallery: getActivityAssets('gannan-ranch-life-light-tour').gallery,
    days: 2,
    durationText: '2天1晚',
    price: 698,
    priceFrom: 698,
    tags: ['草原', '康养', '摄影', '乡村', '文旅'],
    travelModeTags: ['老友聚行', '私人定制', '独自旅行'],
    playTags: ['生态观光', '栖居山野', '创意摄影', '体验派'],
    suitableGroups: ['都市白领', '青年社交族'],
    highlights: ['牧场轻体验', '草原休闲拍照', '风味餐食', '营地氛围'],
    itinerary: [
      'Day1 中午 抵达营地入住',
      'Day1 下午 牧场散步与轻互动体验',
      'Day1 晚上 草原风味晚餐',
      'Day2 上午 自由休闲后返程'
    ],
    pickup: false,
    pickupPoint: '',
    transport: '包车 / 自驾',
    stay: '营地木屋或民宿1晚',
    status: 'published',
    traveledCount: 38
  }
]

function buildSeedRecord(item) {
  return {
    ...item,
    updatedAt: db.serverDate()
  }
}

exports.main = async () => {
  const collection = db.collection('activities')
  const result = {
    total: seedActivities.length,
    created: 0,
    updated: 0,
    ids: []
  }

  for (const item of seedActivities) {
    const queryRes = await collection.where({ seedKey: item.seedKey }).limit(1).get()

    if (queryRes.data.length) {
      const existed = queryRes.data[0]
      await collection.doc(existed._id).update({
        data: buildSeedRecord(item)
      })
      result.updated += 1
      result.ids.push(existed._id)
      continue
    }

    const addRes = await collection.add({
      data: {
        ...buildSeedRecord(item),
        createdAt: db.serverDate()
      }
    })
    result.created += 1
    result.ids.push(addRes._id)
  }

  return {
    success: true,
    message: 'seed activities finished',
    ...result
  }
}
