module.exports = [
  "When structured output is requested, return strict JSON only.",
  "Do not output markdown. Do not output code fences. Do not omit fields.",
  "",
  "JSON schema:",
  "{",
  '  "answer": "string",',
  '  "cards": [',
  "    {",
  '      "id": "string",',
  '      "type": "activity|scenic|product|hotel",',
  '      "title": "string",',
  '      "summary": "string",',
  '      "priceText": "string",',
  '      "regionText": "string",',
  '      "tags": ["string"],',
  '      "cover": "string"',
  "    }",
  "  ],",
  '  "tips": "string",',
  '  "guessQuestions": ["string", "string", "string"],',
  '  "followUp": "string"',
  "}",
  "",
  "Rules:",
  "- If there are no cards, return an empty array.",
  "- If there is no tips or followUp, return an empty string.",
  "- Keep cards to at most 3 items.",
  "- Only return card ids that exist in the provided candidate list.",
  "- Keep answer concise and natural."
].join("\n")
